WIP: Asynchronous interation with Daemon
ZettaScaleLabs/zenoh-flow pull request #1
Opened 2022-08-19 14:45 UTC by gabrik

This PR will contain the code that allows for asynchronous interaction with the daemon.
The idea is that every interaction with the daemon becomes asynchronous.
Eg. The user asks for the instantiation of a Flow (via zfctl), the user immediately gets a `Uuid` identifying the flow, then the daemon will schedule the instantiation via a Job Queue.

The user can check the state of the instantiation using the Flow id provided by the daemon (via zfctl).

2022-08-23 14:30 UTC, gabrik commented
The PR is now ready for review the changelog is:

- Implementation of a Job Queue over Zenoh for asynchronous job execution
- Rename of `Runtime` trait into `DaemonInterface` and split into:`DaemonInterface` for client-to-daemon communication and `DaemonInterfaceInternal` for daemon-to-daemon communications.
- Refactoring of `zenoh-flow-daemon` codebase.

2022-08-30 14:19 UTC, J-Loudet requested changes

2022-08-30 14:19 UTC, J-Loudet commented on zenoh-flow-daemon/src/daemon.rs
> +        // std::future::pending::<()>().await;
To remove?

2022-08-30 14:19 UTC, J-Loudet commented on zenoh-flow-daemon/src/daemon.rs
> +        //@TODO: use Abortable and AbortHandle here.
I’d add the reason why this is still as a TODO and if there is no reason, why not do it?

2022-08-30 14:19 UTC, J-Loudet commented on zenoh-flow-daemon/src/daemon.rs
> +            "[Daemon {}]: Sent job for delete instance {}, JobId: {}",
s/for/to/

If you prefer: "[Daemon: {}][Job: {}] Deleting instance < {} >"?

2022-08-30 14:19 UTC, J-Loudet commented on zenoh-flow-daemon/src/daemon.rs
> +            "[Daemon {}]: Sent job for create instance {}, JobId: {}",
s/for/to/

If you prefer: "[Daemon: {}][Job: {}] Creating instance < {} >"?

2022-08-30 14:19 UTC, J-Loudet commented on zenoh-flow-daemon/src/daemon.rs
> +            "[Daemon {}]: Sent job for instantiate (crate+start) {}, JobId: {}",
s/for/to/

If you prefer: "[Daemon: {}][Job: {}] Instantiating flow < {} >"?

2022-08-30 14:19 UTC, J-Loudet commented on zenoh-flow-daemon/src/daemon.rs
> +            "[Daemon {}]: Sent job for teardown instance (stop+delete) {}, JobId: {}",
(same)

2022-08-30 14:19 UTC, J-Loudet commented on zenoh-flow-daemon/src/daemon.rs
> +            "[Daemon {}]: Sent job for start instance {}, JobId: {}",
(same)

2022-08-30 14:19 UTC, J-Loudet commented on zenoh-flow-daemon/src/daemon.rs
> +            "[Daemon {}]: Sent job to stop instance {}, JobId: {}",
(same)

2022-08-30 14:19 UTC, J-Loudet commented on zenoh-flow-daemon/src/daemon.rs
> +            "[Daemon {}]: Sent job for start node {} in instance {}, JobId: {}",
(same)

2022-08-30 14:19 UTC, J-Loudet commented on zenoh-flow-daemon/src/daemon.rs
> +            "[Daemon {}]: Sent job for start node {} in instance {}, JobId: {}",
(same)

2022-08-30 14:19 UTC, J-Loudet commented on zenoh-flow-daemon/src/runtime.rs
> +        // the caller should not be blocked.
We can remove that TODO no?

2022-08-30 14:19 UTC, J-Loudet commented on zenoh-flow-daemon/src/runtime.rs
> +    }
Why the dead code?

2022-08-30 14:19 UTC, J-Loudet commented on zenoh-flow-daemon/src/worker.rs
> +// This progr&am and the accompanying materials are made available under the
Typo: progr&am

2022-08-30 14:19 UTC, J-Loudet commented on zenoh-flow-daemon/src/runtime.rs
> +use std::collections::HashMap;
To move below the license

2022-08-30 14:19 UTC, J-Loudet commented on zenoh-flow-daemon/src/runtime.rs
> +// This progr&am and the accompanying materials are made available under the
Typo: progr&am

2022-08-30 14:19 UTC, J-Loudet commented on zenoh-flow/src/runtime/resources.rs
> +                    log::warn!("Received delete sample drop it");
I’d write something like: "Received delete sample. Dropping.", without punctuation it looks weird

2022-08-30 15:00 UTC, gabrik commented on zenoh-flow-daemon/src/runtime.rs
> +            status: RuntimeStatusKind::NotReady,
Remove `status` from `RuntimeStatus`

2022-08-30 15:00 UTC, gabrik commented on zenoh-flow-daemon/src/runtime.rs
> +        self.store
Move after `drop(self_state)`

2022-08-30 15:00 UTC, gabrik commented on zenoh-flow-daemon/src/runtime.rs
> +    pub(crate) async fn clean(&self, record_id: Uuid) -> DaemonResult<DataFlowRecord> {
For the future rename `record` into `instance` everywhere to avoid confusion

2022-08-30 15:00 UTC, gabrik commented on zenoh-flow-daemon/src/runtime.rs
> +
Add doc to explain why sources need to be started after all other operators in a multi-runtime scenario.

2022-08-30 15:00 UTC, gabrik commented on zenoh-flow-daemon/src/runtime.rs
> +    }
Comment

2022-08-31 07:14 UTC, gabrik commented on zenoh-flow-daemon/src/runtime.rs
> +    }
Cannot comment them, they are in the `Daemon` trait

2022-08-31 07:18 UTC, gabrik commented on zenoh-flow-daemon/src/runtime.rs
> +    }
They are actually called from `worker.rs:241` and worker.rs:265` not sure why clippy is not happy.

2022-08-31 07:27 UTC, gabrik commented on zenoh-flow-daemon/src/runtime.rs
> +    pub(crate) async fn clean(&self, record_id: Uuid) -> DaemonResult<DataFlowRecord> {
Create this to keep track: https://github.com/eclipse-zenoh/zenoh-flow/issues/119

2022-08-31 07:38 UTC, J-Loudet approved these changes

2022-08-31 08:16 UTC, merged